[[ $- != *i* ]] && return
PS1='[\u@\h \W]\$ '
alias ls='ls --color=auto'
alias l='ls --color=auto'
alias bashrc='vim /home/angel/.bashrc'
alias c='clear'
alias q='exit'
alias reloadrc='source /home/angel/.bashrc'
alias r='fff'
alias i3rc='vim /home/angel/.config/i3/config'
alias cm='cmus'
alias nf='neofetch'
alias birch='bash /home/angel/gtc/birch/birch -s chat.freenode.net -u clydefisher'
alias clock='tty-clock -c -C 7 -D'
alias sic='/home/angel/gtc/sic/sic -n clydefisher -h chat.freenode.net'
