[[ $- != *i* ]] && return
PS1='[\u@\h \W]\$ '
alias lsd='ls -A --color=always --group-directories-first'
alias ls='ls --color=auto'
alias l='ls --color=auto'
alias bashrc='vim /home/confusio/.bashrc'
alias c='clear'
alias q='exit'
alias reloadrc='source /home/confusio/.bashrc'
alias r='fff'
alias cm='cmus'
alias birch='bash /home/confusio/Git-Clone/birch/birch -s chat.freenode.net -u clydefisher'
alias clock='tty-clock -c -C 7 -D'
alias kittyrc='vim /home/confusio/.config/kitty/kitty.conf'
alias herbstrc='vim /home/confusio/.config/herbstluftwm/autostart'
